`timescale 1ns/100ps

// Engineers: Akarsh Ningoji Rao Kolekar - akolekar6@gatech.edu
//		 Abhishek Upadhyay - aupadhyay31@gatech.edu

// This is the Request Generator module of the Switch Allocator.
// It generates a request for a particular output port by an inpnut port.
// Essentially a demultiplexer with the select signal driven by 
// output port generated by route compute unit.

module demux_1to5 (select, op, rst, empty);

input [2:0] select;
output reg [4:0] op;
input rst;
input empty;

always @(select, rst, empty) begin
	if (rst | empty) begin
		op = 5'b00000; // do not generate request if reset is high or the input buffer is empty
	end
	else begin
		case(select)
			3'b000: op = 5'b00001; // north output port requested
			3'b001: op = 5'b00010; // east output port requested
			3'b010: op = 5'b00100; // south output port requested
			3'b011: op = 5'b01000; // west output port requested
			3'b100: op = 5'b10000; // local output port requested
			default: op = 5'b00000;
		endcase
	end
end
endmodule